name: build

on:
  push:
    branches: [main, develop, 8.xx]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main, develop, 8.xx]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        emsdk-version: [3.1.61]
        binaryen-version: [version_117_e]
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: build emulators
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - run: sudo apt-get -yqq update
    - run: sudo apt-get install -yq --no-install-recommends cmake ninja-build zip
    - run: npm install -g yarn
    - run: yarn
    - run: yarn run eslint src --ext ts,tsx --max-warnings 0
    - run: yarn run eslint test --ext ts,tsx --max-warnings 0
    - run: yarn run tsc --noemit
    - run: cd native/sockdrive/js && yarn && yarn run webpack && cd ../../..
    - run: git clone https://github.com/emscripten-core/emsdk.git
    - run: cd emsdk && ./emsdk install ${{ matrix.emsdk-version }} && ./emsdk activate ${{ matrix.emsdk-version }} && cd ..
    - run: wget https://github.com/caiiiycuk/binaryen-fwasm-exceptions/releases/download/${{ matrix.binaryen-version }}/binaryen-${{ matrix.binaryen-version }}-x86_64-linux.tar.gz
    - run: tar xfv binaryen-${{ matrix.binaryen-version }}-x86_64-linux.tar.gz
    - run: cp -v binaryen-${{ matrix.binaryen-version }}/bin/wasm-opt ./emsdk/upstream/bin/wasm-opt
    - run: source ./emsdk/emsdk_env.sh && yarn run gulp production
    - run: zip -9r release.zip dist/*
    
    - name: publish
      if: startsWith(github.ref, 'refs/tags/')
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        
    - name: upload
      uses: actions/upload-artifact@v4.3.6
      with:
        name: 'dist'
        path: 'dist'
        
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref_name }}
        files: |
          ${{github.workspace}}/release.zip
